server:
    port: 8083
spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
                - id: m2-service
                  uri: http://localhost:3002/
                  predicates:
                      - Path=/field2/**
                - id: m1-service
                  uri: http://localhost:3001/
                  predicates:
                      - Path=/field1/**
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    registerWithEureka:
        - true
    fetchRegistry:
        - true
